# Generated by Django 5.0.2 on 2026-04-27 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality', models.IntegerField()),
                ('easiness', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
                ('next_review', models.DateField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Revisão',
                'verbose_name_plural': 'Revisões',
                'db_table': 'estudos_review',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
