# Generated by Django 5.0.2 on 2026-04-27 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudos', '0001_initial'),
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.card'),
        ),
    ]
